### ISSUE TITLE
BUG: Kedro Namespace Pipeline - Error Passing "neptune_run" to node

### ISSUE THREAD

**Issue by adoherty21** [neptune-ai/kedro-neptune#66] opened 2023-05-16 13:23 UTC
### Describe the bug

I am developing a Kedro namespace pipeline and I am using kedro-neptune to track my experiments.

`kedro-neptune` works for basic tracking but I get the following error when I pass `"neptune_run"` as an input to one of my pipeline nodes:

`ValueError: Pipeline input(s) {'NAMESPACE.neptune_run'} not found in the DataCatalog`

Where "NAMESPACE" is the namespace pipeline name.  

Is there a way to log specific values to Neptune when using namespace pipelines?  Within the node I wish to log the following to Neptune:

`neptune_run["evaluation/metrics"] = error_metrics`

I posted this in question on Kedro's Slack and the discussion can be seen [here](https://kedro-org.slack.com/archives/C03RKP2LW64/p1684160873649199).

#### Relevant Libraries:
kedro                                        0.18.8
kedro-neptune                                0.1.6
kedro-viz                                    6.1.0
kedroio                                      0.1.3
neptune                                      1.2.0

Python 3.9.15

**Comment by Blaizzy** [comment] 2023-05-19 13:17
Hey @adoherty21 

Prince here,

Thanks for reaching out!

You can pass a neptune run as input to a node this way:

```python
def create_pipeline(**kwargs) -> Pipeline:
    return pipeline(
        [
            ...,
            node(
                func=report_accuracy,
                inputs=["y_pred", "y_test", "neptune_run"],
                outputs=None,
                name="report_accuracy",
            ),
        ]
    ) 

```
Docs:
https://docs.neptune.ai/integrations/kedro/#setup-and-logging-example

Code example:
https://github.com/neptune-ai/examples/blob/main/integrations-and-supported-tools/kedro/scripts/kedro-neptune-quickstart/src/kedro_neptune_quickstart/pipeline.py

**Comment by adoherty21** [comment] 2023-05-19 13:23
Hi @Blaizzy, thanks a lot for your response.

Yes, the above works for "normal" Kedro Pipelines.  However, when using a Kedro Namespace Pipeline the above does not work and the error I shared in the bug report occurs.

I will work on creating a basic reproducible example.

**Comment by Blaizzy** [comment] 2023-05-22 14:36
Hey @adoherty21 

That would be wonderful,

Looking forward to the reproducible example :)

**Comment by adoherty21** [comment] 2023-05-24 15:25
Good afternoon @Blaizzy, 

I have created a reproducible example which can be found here:

https://github.com/adoherty21/kedro_neptune_namespace_issue

It is a very simple single node example that creates a dataframe and saves to file.  There are two namespace pipelines `namespace_1` and `namespace_2` which create different column names in the saved dataframe.

The following assumes use of Poetry.  Once cloned navigate to the repository and execute the following:

```
poetry env use 3.9
poetry shell
poetry install
kedro neptune init
```

Then add your Neptune project name here:

https://github.com/adoherty21/kedro_neptune_namespace_issue/blob/6abd300ff5980b953e2bebacfc8a00daecb8dbf8/conf/base/neptune.yml#L3

Then run:

`kedro run --pipeline=namespace_1`

Then:

`kedro run --pipeline=namespace_2`

If successful there should be outputs in `data/namespace_1` and `data/namespace_2` at this point.

So far the experiments are logged in Neptune but not are uploading any metadata/files to Neptune.  By uncommenting the following comment the namespace pipeline will attempt to upload the dataframe to Neptune.

https://github.com/adoherty21/kedro_neptune_namespace_issue/blob/6abd300ff5980b953e2bebacfc8a00daecb8dbf8/src/basic_namespace/common/pipelines/common_pipeline_01_raw.py#L12

By running the same commands as before we get the following errors as discussed in my original post:

`ValueError: Pipeline input(s) {'namespace_1.neptune_run'} not found in the DataCatalog`
`ValueError: Pipeline input(s) {'namespace_2.neptune_run'} not found in the DataCatalog`

Let me know if anything is unclear.

Please let me know your thoughts and if there is any fix.

Thanks for your time.

**Comment by SiddhantSadangi** [comment] 2023-05-26 16:02
Hello @adoherty21 ,

First of all, thanks for taking the time to create a reproducible example. I was able to reproduce the issue, and as suspected by you in the Kedro slack [here](https://kedro-org.slack.com/archives/C03RKP2LW64/p1684183540077509?thread_ts=1684160873.649199&cid=C03RKP2LW64), kedro indeed sees this as a dataset rather than a literal. 

I was able to get rid of the `ValueError` by using `partial`:

```python
def create_raw_pipeline() -> Pipeline:
    nodes = [
        node(
            # use partial to pass the string dataset
            # update wrapper to avoid warnings and to improve logging
            func=update_wrapper(
                partial(read_raw_data, neptune_run="neptune_run"), read_raw_data
            ),
            inputs=["params:raw.column_name"],
            outputs="data_raw",
        )
    ]

    return pipeline(nodes, tags="to_raw")
```

However, that introduces the below error due to "neptune_run" being interpreted as a string literal:
![image](https://github.com/neptune-ai/kedro-neptune/assets/41324509/55f37d35-3dbb-4722-be71-ce34c1c6abc9)

_Note: `neptune_run["df"] = df` won't work as dataframes cannot be uploaded to neptune this way. You can upload a dataframe either as an HTML or a CSV as mentioned in our [docs](https://docs.neptune.ai/tools/pandas/#pandas-logging-example)._

This is definitely a bug, and I'll pass this on to our dev team. 
I am also following your thread in Kedro's slack, so I can share any updates there as well in case we need support from Kedro's engineering team.

While our dev team looks into it, will it be possible for you to use normal pipelines instead of namespace pipelines?

**Comment by adoherty21** [comment] 2023-05-26 16:17
Thanks for getting back to me @SiddhantSadangi.  I am glad you could reproduce the error.  The way Kedro interprets strings presents a challenge sometimes. 

Unfortunately I need to use Namespace pipelines for my application. 

I was wondering if the `neptune.run.Handler` object could be imported and then passed to the function using `partial` rather than the string `"neptune_run"`?  I don't know how to access the run handler but if this was exposed that might solve the problem?  

Thanks again.

**Comment by SiddhantSadangi** [comment] 2023-05-29 02:11
We would need to pass the already initialized run to `partial`. Since runs are currently not pickleable, the only way of doing this seems to be to reinitialize the run in the named pipeline using the `custom_run_id` already created by `kedro-neptune`. 

Will check with the devs if/how that can be fetched.

**Comment by adoherty21** [comment] 2023-05-30 08:04
Great @SiddhantSadangi, thanks again.

**Comment by SiddhantSadangi** [comment] 2023-06-01 10:05
Hello @adoherty21,
Sorry for the delay here, we were out on a company retreat :)

We found a workaround that should work

1. Update `common_node_01_raw.py` to below: 

```python
import pandas as pd
import neptune


def read_raw_data(column_name, neptune_run=None):
    df = pd.DataFrame({"index": [1, 2, 3, 4, 5], column_name: [6, 7, 8, 9, 10]})

    if neptune_run:
        neptune_run = neptune.init_run()

        neptune_run["evaluation/metrics"] = 42

    return df

```

2. Update `common_pipeline_01_raw.py` to below:

```python
from kedro.pipeline import Pipeline, node, pipeline

from ..nodes.common_node_01_raw import read_raw_data

from functools import partial, update_wrapper


def create_raw_pipeline() -> Pipeline:
    nodes = [
        node(
            # use partial to pass the string dataset
            # update wrapper to avoid warnings and to improve logging
            func=update_wrapper(
                partial(read_raw_data, neptune_run="neptune_run"), read_raw_data
            ),
            inputs=["params:raw.column_name"],
            outputs="data_raw",
        )
    ]

    return pipeline(nodes, tags="to_raw")
```
3. To upload `data_raw.csv` to Neptune, you can add this to `catalog_raw.yml`:

```yml
namespace_1.data_raw@neptune:
  filepath: data/namespace_1/01_raw/data_raw.csv
  type: kedro_neptune.NeptuneFileDataSet
```

**Note:** 
* This approach will create a neptune run even if `enabled:false` in `neptune.yml`. Fixing this will need an update to the integration that @AleksanderWWW is working on. 
Meanwhile, if you need to disable logging, you can set `enabled:false` and not pass `neptune_run` to `read_raw_data()`
* You might get a few `Timestamp must be non-decreasing for series attribute` errors in `common_node_01_raw.py`. These do not affect logging, and can be suppressed as below:
```python
import logging
...

def read_raw_data(column_name, neptune_run=None):
    ...
    if neptune_run:
        logging.getLogger(
            "neptune.new.internal.operation_processors.async_operation_processor"
        ).setLevel(logging.CRITICAL)

        neptune_run = neptune.init_run()

        ...
```

Please let me know if this works for you.

**Comment by adoherty21** [comment] 2023-06-01 10:08
Great @SiddhantSadangi, thanks a lot for your work on this.  I'll test this in the next few days and I'll get back to you.  Enjoy the retreat!

**Comment by adoherty21** [comment] 2023-06-06 10:53
Sorry for the delay @SiddhantSadangi.  I have now tested and can confirm this works.  Thanks a lot for helping me with this and providing the workaround.  If you could keep me informed with @AleksanderWWW's progress on the permanent solution that would be greatly appreciated.

Feel free to close if you are happy with the interim solution.

Cheers,

Andrew

**Comment by SiddhantSadangi** [comment] 2023-06-06 11:27
Hey @adoherty21 , thanks for the update! Great to know that the workaround works :)

I'll keep this issue open till the fix is merged and verified, and I will keep you updated on the progress.

Meanwhile, please feel free to let us know if you have any other issues/suggestions. We are always happy to help :)

**Closed as completed** 2023-06-06 13:01 UTC
Labels: bug

**Comment by astrojuanlu** [comment] 2023-06-06 13:16
Is there anything that could be improved on the Kedro side, or does gh-68 fully fix this issue?

**Comment by SiddhantSadangi** [comment] 2023-06-06 13:26
From Kedro's end, it would be great if arguments to named pipelines are not assumed to be datasets. That way you can then pass "neptune_run" string as the run handler, which would be consistent with the behavior of "normal" kedro pipelines.

**Comment by astrojuanlu** [comment] 2023-06-06 13:30
Sounds reasonable, could you please open an issue about that over https://github.com/kedro-org/kedro/issues/ @SiddhantSadangi ?

**Comment by SiddhantSadangi** [comment] 2023-06-06 13:41
Done: https://github.com/kedro-org/kedro/issues/2646

**Comment by SiddhantSadangi** [comment] 2023-06-15 08:28
Hello @adoherty21 ,

`kedro-neptune` release [0.2.0](https://github.com/neptune-ai/kedro-neptune/releases/tag/0.2.0) fixed an issue with neptune prevalidations running even if `enabled:false`. 

This should make enabling/disabling neptune easier.

1. Upgrade `kedro-neptune` to 0.2.0
2. Update `common_pipeline_01_raw.py` to:
```python
from kedro.pipeline import Pipeline, node, pipeline

from ..nodes.common_node_01_raw import read_raw_data

def create_raw_pipeline() -> Pipeline:
    nodes = [
        node(
            # use partial to pass the string dataset
            # update wrapper to avoid warnings and to improve logging
            func=read_raw_data, # note: you don't need to pass "neptune_run" anymore
            inputs=["params:raw.column_name"],
            outputs="data_raw",
        )
    ]

    return pipeline(nodes, tags="to_raw")
```

3. Update `common_node_01_raw.py` to:
```python
import pandas as pd
import neptune
import os


def read_raw_data(column_name):
    df = pd.DataFrame({"index": [1, 2, 3, 4, 5], column_name: [6, 7, 8, 9, 10]})

    if os.environ.get("NEPTUNE_CUSTOM_RUN_ID"):
        neptune_run = neptune.init_run()

        neptune_run["evaluation/metrics"] = 42

    return df
```

With these changes,
* You won't need to pass "neptune_run"  to the node, hence avoiding the use of `partial()`
* A neptune run won't be created if the `enabled` flag is set to `false` in `neptune.yml`

Please let me know if this works better for you :)

**Comment by adoherty21** [comment] 2023-06-19 07:38
That looks perfect @SiddhantSadangi.  I'll test this week.
